"""
Excel Datasheet Generator (TEMA Style)
Author: KAKAROTONCLOUD
Version: 3.1.0 Enterprise
"""
import io
import xlsxwriter
from datetime import datetime

def generate_excel_datasheet(res, project_info):
    """
    Generates a professional Excel TEMA-style datasheet in memory.
    """
    output = io.BytesIO()
    workbook = xlsxwriter.Workbook(output, {'in_memory': True})
    sheet = workbook.add_worksheet("Datasheet")

    # --- STYLES ---
    # Header Style
    fmt_header = workbook.add_format({
        'bold': True, 'font_size': 14, 'align': 'center', 'valign': 'vcenter',
        'bg_color': '#1f4e78', 'font_color': 'white', 'border': 1
    })
    # Section Label Style
    fmt_section = workbook.add_format({
        'bold': True, 'bg_color': '#d9e1f2', 'border': 1
    })
    # Parameter Label Style
    fmt_label = workbook.add_format({
        'bold': True, 'align': 'right', 'border': 1, 'bg_color': '#f2f2f2'
    })
    # Data Style
    fmt_data = workbook.add_format({
        'align': 'center', 'border': 1
    })
    # Money Style
    fmt_currency = workbook.add_format({
        'num_format': '$#,##0.00', 'border': 1, 'bg_color': '#e2efda'
    })
    
    # Columns
    sheet.set_column('A:A', 2)   # Margin
    sheet.set_column('B:B', 25)  # Labels
    sheet.set_column('C:C', 20)  # Hot Side
    sheet.set_column('D:D', 20)  # Cold Side
    
    # --- TITLE BLOCK ---
    sheet.merge_range('B2:D3', "HEAT EXCHANGER SPECIFICATION SHEET", fmt_header)
    sheet.write('B4', "Project:", fmt_label)
    sheet.merge_range('C4:D4', project_info.get('project_name', 'Untitled'), fmt_data)
    sheet.write('B5', "Date:", fmt_label)
    sheet.merge_range('C5:D5', datetime.now().strftime('%Y-%m-%d'), fmt_data)
    
    # --- PERFORMANCE ---
    row = 7
    sheet.merge_range(row, 1, row, 3, "1. PERFORMANCE DATA", fmt_section)
    row += 1
    sheet.write(row, 1, "PARAMETER", fmt_label)
    sheet.write(row, 2, "HOT SIDE", fmt_label)
    sheet.write(row, 3, "COLD SIDE", fmt_label)
    row += 1
    
    # Data Loop
    data_rows = [
        ("Fluid", res.get('hot_fluid'), res.get('cold_fluid')),
        ("Flow Rate (kg/s)", res.get('m_hot'), res.get('m_cold')),
        ("Inlet Temp (°C)", res.get('T_hot_in'), res.get('T_cold_in')),
        ("Outlet Temp (°C)", res.get('T_hot_out'), res.get('T_cold_out')),
    ]
    
    for label, h, c in data_rows:
        sheet.write(row, 1, label, fmt_label)
        sheet.write(row, 2, h, fmt_data)
        sheet.write(row, 3, c, fmt_data)
        row += 1
        
    # Calculated
    sheet.write(row, 1, "Duty (kW)", fmt_label)
    sheet.merge_range(row, 2, row, 3, res.get('Q', 0), fmt_data)
    row += 1
    sheet.write(row, 1, "LMTD (°C)", fmt_label)
    sheet.merge_range(row, 2, row, 3, res.get('LMTD', 0), fmt_data)
    row += 1
    
    # --- MECHANICAL ---
    row += 1
    sheet.merge_range(row, 1, row, 3, "2. MECHANICAL & HYDRAULIC", fmt_section)
    row += 1
    
    hyd = res.get('hydraulics', {})
    meta = res.get('meta', {})
    
    mech_rows = [
        ("Configuration", meta.get('config', 'N/A')),
        ("Surface Area (m²)", res.get('area', 0)),
        ("Tube Velocity (m/s)", hyd.get('velocity_m_s', 0)),
        ("Pressure Drop (kPa)", hyd.get('pressure_drop_kPa', 0)),
        ("Flow Regime", hyd.get('regime', 'N/A'))
    ]
    
    for label, val in mech_rows:
        sheet.write(row, 1, label, fmt_label)
        sheet.merge_range(row, 2, row, 3, val, fmt_data)
        row += 1
        
    # --- COST ---
    row += 1
    sheet.merge_range(row, 1, row, 3, "3. ESTIMATED COST (Class 4)", fmt_section)
    row += 1
    
    fin = res.get('financials', {})
    cost_rows = [
        ("Equipment (FOB)", fin.get('equipment_fob', 0)),
        ("Installation", fin.get('installation', 0)),
        ("TOTAL CAPEX", fin.get('total_capex', 0))
    ]
    
    for label, val in cost_rows:
        sheet.write(row, 1, label, fmt_label)
        sheet.merge_range(row, 2, row, 3, val, fmt_currency)
        row += 1

    # Footer
    row += 2
    sheet.merge_range(row, 1, row, 3, "Generated by ExchangerPro | KAKAROTONCLOUD", 
                      workbook.add_format({'italic': True, 'align': 'center', 'color': 'gray'}))

    workbook.close()
    output.seek(0)
    return output
