"""
Excel Datasheet Generator (TEMA Style)
Author: KAKAROTONCLOUD
Version: 3.0.0 Enterprise
"""
import io
import xlsxwriter
from datetime import datetime

def generate_excel_datasheet(res, project_info):
    """
    Generates a professional Excel TEMA-style datasheet in memory.
    """
    output = io.BytesIO()
    workbook = xlsxwriter.Workbook(output, {'in_memory': True})
    sheet = workbook.add_worksheet("TEMA Datasheet")

    # --- FORMATS ---
    bold_header = workbook.add_format({'bold': True, 'font_size': 14, 'align': 'center', 'bg_color': '#D9E1F2', 'border': 1})
    section_header = workbook.add_format({'bold': True, 'font_size': 11, 'bg_color': '#D9D9D9', 'border': 1})
    label_fmt = workbook.add_format({'bold': True, 'align': 'right', 'border': 1})
    data_fmt = workbook.add_format({'align': 'left', 'border': 1})
    center_fmt = workbook.add_format({'align': 'center', 'border': 1})
    num_fmt = workbook.add_format({'num_format': '#,##0.00', 'border': 1})
    
    # Set Column Widths
    sheet.set_column('A:A', 5)   # Margin
    sheet.set_column('B:B', 25)  # Labels
    sheet.set_column('C:C', 20)  # Data 1
    sheet.set_column('D:D', 20)  # Data 2
    
    # --- HEADER ---
    sheet.merge_range('B2:D2', "HEAT EXCHANGER SPECIFICATION SHEET", bold_header)
    sheet.write('B3', "Project:", label_fmt)
    sheet.merge_range('C3:D3', project_info.get('project_name', 'Untitled'), data_fmt)
    sheet.write('B4', "Date:", label_fmt)
    sheet.merge_range('C4:D4', datetime.now().strftime('%Y-%m-%d'), data_fmt)
    
    # --- 1. PERFORMANCE DATA ---
    row = 6
    sheet.merge_range(row, 1, row, 3, "1. PERFORMANCE DATA", section_header)
    row += 1
    
    # Headers
    sheet.write(row, 1, "PARAMETER", center_fmt)
    sheet.write(row, 2, "HOT SIDE", center_fmt)
    sheet.write(row, 3, "COLD SIDE", center_fmt)
    row += 1
    
    # Data Rows
    items = [
        ("Fluid Name", res.get('hot_fluid'), res.get('cold_fluid')),
        ("Flow Rate (kg/s)", res.get('m_hot'), res.get('m_cold')),
        ("Inlet Temp (°C)", res.get('T_hot_in'), res.get('T_cold_in')),
        ("Outlet Temp (°C)", res.get('T_hot_out'), res.get('T_cold_out')),
    ]
    
    for label, h_val, c_val in items:
        sheet.write(row, 1, label, label_fmt)
        sheet.write(row, 2, h_val, num_fmt if isinstance(h_val, (int, float)) else center_fmt)
        sheet.write(row, 3, c_val, num_fmt if isinstance(c_val, (int, float)) else center_fmt)
        row += 1
        
    # Calculated Performance
    sheet.write(row, 1, "Total Heat Duty (kW)", label_fmt)
    sheet.merge_range(row, 2, row, 3, res.get('Q', 0), num_fmt)
    row += 1
    sheet.write(row, 1, "LMTD (°C)", label_fmt)
    sheet.merge_range(row, 2, row, 3, res.get('LMTD', 0), num_fmt)
    row += 1
    
    # --- 2. CONSTRUCTION DATA ---
    row += 1
    sheet.merge_range(row, 1, row, 3, "2. CONSTRUCTION & HYDRAULICS", section_header)
    row += 1
    
    meta = res.get('meta', {})
    hyd = res.get('hydraulics', {})
    
    const_items = [
        ("Configuration", meta.get('config', 'N/A')),
        ("Material", meta.get('material', 'N/A')),
        ("Fouling Factor", meta.get('fouling', 0)),
        ("Required Area (m²)", res.get('area', 0)),
        ("Tube Velocity (m/s)", hyd.get('velocity_m_s', 0)),
        ("Pressure Drop (kPa)", hyd.get('pressure_drop_kPa', 0)),
        ("Flow Regime", hyd.get('regime', 'N/A'))
    ]
    
    for label, val in const_items:
        sheet.write(row, 1, label, label_fmt)
        if isinstance(val, (int, float)):
            sheet.merge_range(row, 2, row, 3, val, num_fmt)
        else:
            sheet.merge_range(row, 2, row, 3, val, center_fmt)
        row += 1

    # --- 3. COST ESTIMATE ---
    row += 1
    sheet.merge_range(row, 1, row, 3, "3. PRELIMINARY COST ESTIMATE (Class 4)", section_header)
    row += 1
    
    fin = res.get('financials', {})
    
    cost_items = [
        ("Equipment Cost (FOB)", fin.get('equipment_fob', 0)),
        ("Installation Labor", fin.get('installation', 0)),
        ("Indirects & Eng.", fin.get('indirects', 0)),
        ("TOTAL CAPEX (USD)", fin.get('total_capex', 0))
    ]
    
    for label, val in cost_items:
        sheet.write(row, 1, label, label_fmt)
        sheet.merge_range(row, 2, row, 3, val, workbook.add_format({'num_format': '$#,##0.00', 'border': 1, 'bg_color': '#E2EFDA'}))
        row += 1

    # Footer
    row += 2
    sheet.merge_range(row, 1, row, 3, "Generated by ExchangerPro | KAKAROTONCLOUD", workbook.add_format({'italic': True, 'align': 'center', 'font_color': '#808080'}))

    workbook.close()
    output.seek(0)
    return output

