"""
Engineering Specification Generator
Author: KAKAROTONCLOUD
Version: 3.0.0 Enterprise
"""
from datetime import datetime

def generate_text_report(res, hyd, fin, meta, project_info):
    """
    Generates a TEMA-style text specification sheet.
    """
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    p_name = project_info.get('project_name', 'Untitled Project')
    
    # Helper for formatting
    def f(val, d=2): 
        try: return f"{float(val):,.{d}f}"
        except: return "N/A"

    lines = []
    lines.append("======================================================================")
    lines.append(" HEAT EXCHANGER SPECIFICATION SHEET")
    lines.append(" Generated by ExchangerPro (KAKAROTONCLOUD)")
    lines.append("======================================================================")
    lines.append(f" Project:      {p_name}")
    lines.append(f" Date:         {timestamp}")
    lines.append(f" Item Tag:     HX-001 (Typical)")
    lines.append("-" * 70)
    lines.append("")

    lines.append("1. GENERAL DATA")
    lines.append(f"   Exchanger Type:      {meta.get('config', 'N/A')}")
    lines.append(f"   Flow Arrangement:    {res.get('flow_type', 'N/A')}")
    lines.append(f"   Design Duty:         {f(res.get('Q', 0))} kW")
    lines.append(f"   Required Area:       {f(res.get('area', 0))} m2")
    lines.append(f"   Design U-Value:      {f(res.get('U_value', 0), 0)} W/m2-K")
    lines.append("")

    lines.append("2. PERFORMANCE DATA")
    lines.append("   PARAMETER             | HOT SIDE             | COLD SIDE")
    lines.append("   ----------------------|----------------------|---------------------")
    lines.append(f"   Fluid                 | {res.get('hot_fluid'):<20} | {res.get('cold_fluid')}")
    lines.append(f"   Flow Rate (kg/s)      | {f(res.get('m_hot')):<20} | {f(res.get('m_cold'))}")
    lines.append(f"   Inlet Temp (C)        | {f(res.get('T_hot_in')):<20} | {f(res.get('T_cold_in'))}")
    lines.append(f"   Outlet Temp (C)       | {f(res.get('T_hot_out')):<20} | {f(res.get('T_cold_out'))}")
    lines.append("")
    lines.append(f"   LMTD: {f(res.get('LMTD'))} C   |   Effectiveness: {f(res.get('effectiveness')*100, 1)} %")
    lines.append("")

    lines.append("3. HYDRAULIC & MECHANICAL")
    lines.append(f"   Material:            {meta.get('material')}")
    lines.append(f"   Fouling Factor:      {meta.get('fouling')} m2-K/W")
    if hyd:
        lines.append(f"   Tube Velocity:       {f(hyd.get('velocity_m_s'))} m/s")
        lines.append(f"   Reynolds Number:     {f(hyd.get('reynolds'), 0)}")
        lines.append(f"   Flow Regime:         {hyd.get('regime')}")
        lines.append(f"   Calc Pressure Drop:  {f(hyd.get('pressure_drop_kPa'))} kPa")
    lines.append("")

    lines.append("4. COST ESTIMATE (Class 4)")
    lines.append(f"   Equipment (FOB):     $ {f(fin.get('equipment_fob'))}")
    lines.append(f"   Installation:        $ {f(fin.get('installation'))}")
    lines.append(f"   Total Installed:     $ {f(fin.get('total_capex'))}")
    lines.append("")

    # Warning Section
    warnings = res.get('warnings', []) + (hyd.get('alerts', []) if hyd else [])
    if warnings:
        lines.append("!!! DESIGN ALERTS !!!")
        for w in warnings:
            lines.append(f"   [WARN] {w}")
    else:
        lines.append("Status: Design Acceptable (No Violations)")

    lines.append("")
    lines.append("="*70)
    lines.append(" End of Specification")
    
    return "\n".join(lines)
